= [[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
=== Business Context

This Application needs to integrate into a landscape of preexisting websites for convention management and needs to
compete with equally designed solutions for the same problem.

However, in itself, this project doesn't have any kind of business context, since it's a standalone project with no
outer bounds or restrictions other than the ones that are applied by the project itself.

=== Technical Context

Since this project doesn't have any outer dependencies all context is solely from the frontend to the backend. Hence
all the APIs that are documented here, are only used by the frontend.

==== Character APIs

===== Character Overview API
Gets an overview data for all characters of a specific user.

====== Request
GET `.../api/character_overview/<user_id>`

====== Parameters
* *user_id*: The ID of the user whose characters should be listed.

====== Response
Array of character objects, each containing the following fields:

* *id*: ID of the character
* *name*: Name of the character.
* *profession*: Profession the character follows.
* *group*: Group the character belongs to.


===== Character API
Gets a detailed view on one specific character.

====== Request
GET `.../api/character/<character_id>`

====== Parameters
* *character_id*: The id of the character whose information should be listed.

====== Response
Object containing multiple fields with character information:

* *name*: Name of the character.
* *profession*: Profession the character follows.
* *group*: Group the character belongs to.
* *(details)*: Multiple fields with more information (WIP).

===== Character Save API
Saves a character after editing it.

====== Request
POST `.../api/character_save/<character_id>`

====== Parameters
* *character_id*: ID of the character that is to be saved.

The information about the character are delivered as json in the request body as documented as in _Character API_.

====== Response
One of the following:

* *Status code 200*: If all went well and the character was saved.
* *Status code 404*: If the character could not be found.

===== Character Create API
Creates a previously non-existing character.

====== Request
POST `.../api/character_create/`

====== Parameters
As json in request body:

* *name*: Name of the character that is to be created.
* *user_id*: ID of the user to which the character should be linked.

====== Response
One of the following:

* *Status code 200*: If all went well and the character was created.
* *Status code 404*: If the user could not be found or the character name is empty.

===== Character Delete API
Deletes a specific character.

====== Request
POST `.../api/character_delete/<character_id>`

====== Parameters
* *character_id*: ID of the character that is to be deleted.

====== Response
* *Status code 200*: If all went well and the character was deleted.
* *Status code 404*: If the character could not be found.
